#!/bin/bash
#SBATCH --job-name=ddp
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --partition=vgpu20
#SBATCH --gres=gpu:1
conda activate ~/torch
python3 /home/Student/s4606685/vqvae_11_1/vqvae_train.py 
